apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: hmnary82/edu4
  newTag: v2
- name: shclub/edu4
  newTag: v1
namePrefix: dev-
#commonLabels:
#  variants: development
patchesStrategicMerge:
- replica_count.yaml
- cpu_count.yaml
resources:
- ../../base
